<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Core\ClopeEngine — копия.cs" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="DataStorage\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="MSTest.TestFramework" Version="4.3.0" />
  </ItemGroup>

</Project>
